version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
      args:
          JAR_FILE: target/tournament-manager-backend-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://db:1433;databaseName=master;encrypt=true;trustServerCertificate=true;
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME:-sa}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-SecureP@ssw0rd!}
      APP_JWT_SECRET: ${JWT_SECRET:-61537c32b3b70252a3244469fa6a87c1befcf86694d174af82b0173a0d64750d21701bd6e5370bb5d69d64b0db6fdba943166da1b0276d703a86d1ee4b53165e}
      APP_JWT_EXPIRATION_MILLISECONDS: ${JWT_EXPIRATION:-86400000}
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: ${DB_PASSWORD:-SecureP@ssw0rd!}
      ACCEPT_EULA: "Y"
    volumes:
      - db_data:/var/opt/mssql
volumes:
  db_data: