version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
      args:
          JAR_FILE: target/tournament-manager-backend-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://db:1433;databaseName=TournamentDB;encrypt=false;trustServerCertificate=true;
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: ${SA_PASSWORD}
      APP_JWT_SECRET: ${JWT_SECRET:-61537c32b3b70252a3244469fa6a87c1befcf86694d174af82b0173a0d64750d21701bd6e5370bb5d69d64b0db6fdba943166da1b0276d703a86d1ee4b53165e}
      APP_JWT_EXPIRATION_MILLISECONDS: ${JWT_EXPIRATION:-86400000}
    depends_on:
      db:
        condition: service_healthy
  db:
    build: ./database-server
    container_name: mssql_server
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${DB_PASSWORD:-SecureP@ssw0rd!}
    volumes:
      - db_data:/var/opt/mssql
      - db_backup:/var/opt/mssql/backup
    ports:
      - "1433:1433"
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "${SA_PASSWORD}", "-Q", "SELECT 1" ]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 20s
  db-maintenance:
    build: ./database-maintenance
    container_name: mssql_maintenance
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      DB_HOST: db
      DB_NAME: TournamentDB
    volumes:
      - db_backup:/var/opt/mssql/backup
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
  db_backup: